# Generated by Django 5.2.7 on 2025-11-20 21:28

# Generated by Django 5.2.7 on 2025-11-20 21:28

from django.db import migrations


def clean_dogs_allowed_forwards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        "ALTER TABLE trails_api_trail ALTER COLUMN dogs_allowed DROP NOT NULL;"
    )
    schema_editor.execute(
        "UPDATE trails_api_trail SET dogs_allowed = NULL WHERE dogs_allowed::TEXT = '';"
    )


def clean_dogs_allowed_backwards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        "ALTER TABLE trails_api_trail ALTER COLUMN dogs_allowed SET NOT NULL;"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0013_alter_trail_dogs_allowed'),
    ]

    operations = [
        migrations.RunPython(
            clean_dogs_allowed_forwards,
            clean_dogs_allowed_backwards,
        ),
    ]
