# Generated by Django 5.2.7 on 2025-11-20 21:28

# Generated by Django 5.2.7 on 2025-11-20 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0013_alter_trail_dogs_allowed'),
    ]

    operations = [
        # First, remove NOT NULL constraint
        migrations.RunSQL(
            "ALTER TABLE trails_api_trail ALTER COLUMN dogs_allowed DROP NOT NULL;",
            "ALTER TABLE trails_api_trail ALTER COLUMN dogs_allowed SET NOT NULL;",
        ),
        # Then clean the data
        migrations.RunSQL(
            "UPDATE trails_api_trail SET dogs_allowed = NULL WHERE dogs_allowed::TEXT = '';",
            migrations.RunSQL.noop,
        ),
    ]
