# Generated by Django 5.2.7 on 2025-11-20 21:30

import django.contrib.gis.db.models.fields
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0014_clean_dogs_allowed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='town',
            options={'ordering': ['name'], 'verbose_name': 'Town', 'verbose_name_plural': 'Towns'},
        ),
        migrations.AddField(
            model_name='town',
            name='country',
            field=models.CharField(db_index=True, default='Ireland', max_length=100),
        ),
        migrations.AddField(
            model_name='town',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='town',
            name='elevation_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='gdp_per_capita',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='is_capital',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='town',
            name='unemployment_rate',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='town',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='area',
            field=models.FloatField(blank=True, help_text='Area in km²', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='town',
            name='population',
            field=models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='town',
            name='town_type',
            field=models.CharField(blank=True, choices=[('capital', 'Capital'), ('city', 'City'), ('town', 'Town'), ('village', 'Village')], default='town', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], db_index=True, default='moderate', max_length=100),
        ),
        migrations.AlterField(
            model_name='trail',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, help_text='Trail length in kilometers', max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='trail',
            name='dogs_allowed',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='elevation_gain_m',
            field=models.IntegerField(help_text='Total elevation gain in meters', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='trail',
            name='start_point',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Trail start coordinates (longitude, latitude)', srid=4326),
        ),
        migrations.AddIndex(
            model_name='town',
            index=models.Index(fields=['country'], name='town_country_idx'),
        ),
        migrations.AddIndex(
            model_name='town',
            index=models.Index(fields=['population'], name='town_population_idx'),
        ),
    ]
