# Generated by Django 5.2.7 on 2025-11-28 22:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0016_poi_boundaries'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pointofinterest',
            new_name='trails_api__poi_typ_718084_idx',
            old_name='poi_type_county_idx',
        ),
        migrations.RenameIndex(
            model_name='trailpoiintersection',
            new_name='trails_api__trail_i_223cd5_idx',
            old_name='trail_prox_idx',
        ),
        migrations.RenameIndex(
            model_name='trailpoiintersection',
            new_name='trails_api__poi_id_68da57_idx',
            old_name='poi_dist_idx',
        ),
        migrations.AlterField(
            model_name='geographicboundary',
            name='boundary_type',
            field=models.CharField(choices=[('county', 'County'), ('region', 'Region'), ('protected_area', 'Protected Area'), ('national_park', 'National Park'), ('nature_reserve', 'Nature Reserve'), ('forest', 'Forest'), ('river', 'River'), ('marine_protected', 'Marine Protected Area')], max_length=50),
        ),
        migrations.AlterField(
            model_name='geographicboundary',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(db_index=True, geography=True, srid=4326),
        ),
    ]
