# Generated by Django 5.2.7 on 2025-11-29 01:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0017_rename_poi_type_county_idx_trails_api__poi_typ_718084_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='path',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326),
        ),
    ]
