# Generated by Django 5.2.7 on 2025-12-06 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0018_alter_trail_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeographicBoundary',
            new_name='Rivers',
        ),
        migrations.AlterModelTable(
            name='rivers',
            table='trails_api_geographicboundary',
        ),
    ]
