# Generated by Django 5.2.7 on 2026-02-14 18:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0019_rename_geographicboundary_rivers_alter_rivers_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('accommodation_source', models.CharField(choices=[('airbnb', 'Airbnb'), ('booking', 'Booking.com'), ('trivago', 'Trivago'), ('manual', 'Manual Entry')], db_index=True, max_length=50)),
                ('external_id', models.CharField(help_text='Unique ID from external source', max_length=100, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(db_index=True, geography=True, srid=4326)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='trail',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('scraped', 'Auto-Scraped'), ('pending', 'Pending'), ('missing', 'Missing')], db_index=True, default='missing', max_length=20),
        ),
    ]
