# Generated by Django 5.2.7 on 2026-03-07 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails_api', '0021_rename_accommodation_source_accommodation_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='accommodation_source',
            new_name='source',
        ),
        migrations.AddField(
            model_name='trail',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for rejection reason', null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_trails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trail',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('scraped', 'Auto-Scraped'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('missing', 'Missing')], db_index=True, default='missing', max_length=20),
        ),
    ]
