options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the Docker image used for testing and deployment
  - name: 'gcr.io/cloud-builders/docker'
    id: 'BuildImage'
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/long-octane-477515-k6/cloud-run-source-deploy/stay-and-trek-service:latest
      - . # Assumes Dockerfile is in the root directory. Adjust 'dir' if it's elsewhere.

  # Step 2: Run Django automated tests inside the built application image.
  # If tests fail here, Cloud Build stops and deployment is blocked.
  - name: 'gcr.io/cloud-builders/docker'
    id: RunDjangoTests
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          echo "Running Django automated tests..."
          docker run --rm \
            -e SECRET_KEY=test-secret-key \
            -e DEBUG=0 \
            -e DJANGO_SETTINGS_MODULE=webmapping_project.settings_ci \
            -e SPATIALITE_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/mod_spatialite.so \
            europe-west1-docker.pkg.dev/long-octane-477515-k6/cloud-run-source-deploy/stay-and-trek-service:latest \
            python manage.py test trails_api.tests.test_models trails_api.tests.test_filters trails_api.tests.test_api trails_api.tests.test_views trails_api.tests.test_integration -v 2

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'PushImage'
    args:
      - push
      - europe-west1-docker.pkg.dev/long-octane-477515-k6/cloud-run-source-deploy/stay-and-trek-service:latest

  # Step 5: Deploy the new image to Cloud Run
  # This step will ONLY run if all preceding test and build/push steps are successful.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'DeployToCloudRun'
    args:
      - gcloud
      - run
      - deploy
      - stay-and-trek-service
      - --image
      - europe-west1-docker.pkg.dev/long-octane-477515-k6/cloud-run-source-deploy/stay-and-trek-service:latest
      - --region
      - europe-west1
      - --add-cloudsql-instances=long-octane-477515-k6:europe-west1:stay-trek-db
      - --service-account
      - cloud-run-service-account@${PROJECT_ID}.iam.gserviceaccount.com
      - --set-secrets=MY_API_KEY=api_key_secret:latest
      - --set-env-vars=ACTIVE_DB=new
      - --set-env-vars=NEW_DB_NAME=trails_db
      - --set-env-vars=NEW_DB_USER=postgres
      - --set-env-vars=NEW_DB_HOST=/cloudsql/long-octane-477515-k6:europe-west1:stay-trek-db
      - --set-env-vars=SECRET_KEY=django-insecure-nehw-)k@fa!el1zw5jdj#bn-x&@c)ph7sjd7i%%91$xwrcze)b
      - --set-env-vars=OPENWEATHERMAP_API_KEY=d7f38f79ac1c83a0ed6867548326ece9
      - --set-secrets=NEW_DB_PASSWORD=cloud_sql_password:latest
      - --allow-unauthenticated
    env:
      - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'

images:
  - europe-west1-docker.pkg.dev/long-octane-477515-k6/cloud-run-source-deploy/stay-and-trek-service:latest
