# Generated by Django 5.2.7 on 2025-11-15 20:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolygonAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon_geojson', models.TextField(help_text='GeoJSON polygon data')),
                ('polygon_geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='PostGIS polygon geometry', srid=4326)),
                ('cities_count', models.IntegerField(help_text='Number of cities found')),
                ('total_population', models.BigIntegerField(help_text='Total population in polygon')),
                ('average_population', models.FloatField(help_text='Average population')),
                ('area_analyzed_km2', models.FloatField(help_text='Polygon area in km²')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('query_duration_ms', models.IntegerField(help_text='Query execution time')),
            ],
            options={
                'verbose_name': 'Polygon Analysis',
                'verbose_name_plural': 'Polygon Analyses',
                'ordering': ['-analysis_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('total_searches', models.IntegerField(default=0)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvancedCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City name', max_length=100)),
                ('country', models.CharField(help_text='Country name', max_length=100)),
                ('population', models.IntegerField(help_text='City population')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('area_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Geographic location as Point', srid=4326)),
                ('elevation_m', models.IntegerField(blank=True, null=True)),
                ('gdp_per_capita', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unemployment_rate', models.FloatField(blank=True, null=True)),
                ('city_type', models.CharField(choices=[('capital', 'Capital City'), ('major', 'Major City'), ('medium', 'Medium City'), ('small', 'Small City'), ('town', 'Town')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advanced City',
                'verbose_name_plural': 'Advanced Cities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['population'], name='advanced_js_populat_1f1af0_idx'), models.Index(fields=['country'], name='advanced_js_country_044a1e_idx')],
            },
        ),
    ]
