"""
Django settings for webmapping_project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path
import os
import ctypes

# Try to load environment variables from a .env file if python-dotenv is installed.
# This keeps the app from crashing if the package isn't available in the environment.
try:
    from dotenv import load_dotenv
except Exception:
    load_dotenv = None

if load_dotenv:
    try:
        load_dotenv()
    except Exception:
        # silently continue if loading the file fails
        pass


BASE_DIR = Path(__file__).resolve().parent.parent

# --- Geo stack paths (platform-aware) ---
# Django/GeoDjango will auto-detect GDAL/GEOS at runtime
# Only set paths, don't try to preload the libraries
import platform

if platform.system() == "Darwin":
    # macOS development (Apple Silicon Homebrew)
    # Try the specific version first, then fall back to generic name
    os.environ["GDAL_LIBRARY_PATH"] = "/opt/homebrew/lib/libgdal.37.dylib"
    os.environ["GEOS_LIBRARY_PATH"] = "/opt/homebrew/opt/geos/lib/libgeos_c.dylib"
    os.environ["PROJ_LIB"] = "/opt/homebrew/opt/proj/share/proj"
else:
    # Linux (Docker/production) - rely on system libraries
    os.environ["PROJ_LIB"] = "/usr/share/proj"
    # Django will find these automatically



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
OPENWEATHERMAP_API_KEY = os.getenv('OPENWEATHERMAP_API_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']  # Allow all hosts for demo/checkpoint

CSRF_TRUSTED_ORIGINS = [
    "https://stay-and-trek.com",
    "https://www.stay-and-trek.com",
    "https://stay-and-trek-service-642845720185.europe-west1.run.app",
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    
    # GeoDjango
    'django.contrib.gis',
    
    # Leaflet
    'leaflet',
    
    # Third party
    'rest_framework',
    'rest_framework_gis',
    'django_filters',
    'corsheaders',
    'drf_spectacular',
    "drf_spectacular_sidecar",
    
    # Local apps
    'maps',
    
    #New app from week 3
    'trails_api', # Trails API
    
    
    # Dashboard
    'dashboard',
    'advanced_js_mapping',
    
    'django.contrib.humanize',
    # Authentication app
    'authentication'
    
    
]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = 'webmapping_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [BASE_DIR / 'templates'],
        'DIRS': [ BASE_DIR / 'templates', BASE_DIR / 'webmapping_project' / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webmapping_project.wsgi.application'


if os.getenv("CI"):
    print("🔹 Using SpatiaLite (SQLite GIS) for CI build")
    os.environ["SPATIALITE_LIBRARY_PATH"] = "mod_spatialite"
    DATABASES = {
        "default": {
            "ENGINE": "django.contrib.gis.db.backends.spatialite",
            "NAME": ":memory:",
        }
    }
else:
    # Detect which database to use: local PostGIS or Cloud SQL
    # environment variables should already be loaded above if python-dotenv is present

    if os.getenv("ACTIVE_DB") == "new":
        print("🔹 Using Cloud SQL (PostgreSQL 17)")
        DATABASES = {
            'default': {
                'ENGINE': 'django.contrib.gis.db.backends.postgis',
                'NAME': os.getenv('NEW_DB_NAME'),
                'USER': os.getenv('NEW_DB_USER'),
                'PASSWORD': os.getenv('NEW_DB_PASSWORD'),
                'HOST': os.getenv('NEW_DB_HOST'),
                'PORT': os.getenv('NEW_DB_PORT'),
            }
        }
    else:
        print("🔹 Using local PostGIS (default)")
        # Check if running in Docker (env vars set by docker-compose)
        if os.getenv('DATABASE_URL'):
            # Docker environment - use docker-compose variables
            DATABASES = {
                'default': {
                    'ENGINE': 'django.contrib.gis.db.backends.postgis',
                    'NAME': os.getenv('POSTGRES_DB', 'trails_db'),
                    'USER': os.getenv('POSTGRES_USER', 'postgres'),
                    'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
                    'HOST': os.getenv('DB_HOST', 'db'),  # Docker service name
                    'PORT': os.getenv('DB_PORT', '5432'),
                }
            }
        else:
            # Local development (macOS)
            DATABASES = {
                'default': {
                    'ENGINE': 'django.contrib.gis.db.backends.postgis',
                    'NAME': 'webmapping_db',
                    'USER': 'aaronbaggot',
                    'PASSWORD': '',
                    'HOST': 'localhost',
                    'PORT': '5432',
                }
            }


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# //DATABASES = {
#     'default': {
#         'ENGINE': 'django.contrib.gis.db.backends.postgis',
#         'NAME': 'trails_db',      #  match your docker-compose service
#         'USER': 'postgres',       # match docker-compose credentials
#         'PASSWORD': 'postgres',
#         'HOST': 'db',             # internal hostname for the Postgres container
#         'PORT': '5432',
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Open for development
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# CORS settings for development
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# API Documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'Trials API',
    'DESCRIPTION': 'RESTful API for trial data in Ireland',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    "CONTACT": {"name": "Aaron Baggot", "programme": "TU856", "Module": "Web Mapping", "email": "C22716399@mytudublin.ie"},
    "LICENSE": {"name": "MIT"},
    
    # Optional niceties:
    "COMPONENT_SPLIT_REQUEST": True,
    "SWAGGER_UI_SETTINGS": {"deepLinking": True, "displayOperationId": True},


}



LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (53.3498, -6.2603),  # Dublin coordinates
    'DEFAULT_ZOOM': 7,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,
    'SCALE': 'both',
}


# Authentication Configuration
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/advanced-js-mapping/'
LOGOUT_REDIRECT_URL = '/advanced-js-mapping/'






