"""
Django settings for webmapping_project project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path
from dotenv import load_dotenv
import os
import ctypes
load_dotenv()


BASE_DIR = Path(__file__).resolve().parent.parent

# --- Geo stack absolute paths (Homebrew on Apple Silicon) ---
GDAL_LIBRARY_PATH = "/opt/homebrew/lib/libgdal.dylib"
GEOS_LIBRARY_PATH = "/opt/homebrew/opt/geos/lib/libgeos_c.dylib"

# PROJ is looked up via env var (fine to set here too)
import os
os.environ["PROJ_LIB"] = "/opt/homebrew/opt/proj/share/proj"

ctypes.CDLL(os.environ["GEOS_LIBRARY_PATH"])
ctypes.CDLL(os.environ["GDAL_LIBRARY_PATH"])



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
OPENWEATHERMAP_API_KEY = os.getenv('OPENWEATHERMAP_API_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    
    # GeoDjango
    'django.contrib.gis',
    
    # Leaflet
    'leaflet',
    
    # Third party
    'rest_framework',
    'rest_framework_gis',
    'django_filters',
    'corsheaders',
    'drf_spectacular',
    "drf_spectacular_sidecar",
    
    # Local apps
    'maps',
    
    #New app from week 3
    'trails_api', # Trails API
    
    
    # Dashboard
    'dashboard',
    
    'django.contrib.humanize',
    
    
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webmapping_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webmapping_project.wsgi.application'


if os.getenv("CI"):
    print("🔹 Using SpatiaLite (SQLite GIS) for CI build")
    os.environ["SPATIALITE_LIBRARY_PATH"] = "mod_spatialite"
    DATABASES = {
        "default": {
            "ENGINE": "django.contrib.gis.db.backends.spatialite",
            "NAME": ":memory:",
        }
    }
else:
    # Detect which database to use: local PostGIS or Cloud SQL
    from dotenv import load_dotenv
    import os
    load_dotenv()

    if os.getenv("ACTIVE_DB") == "new":
        print("🔹 Using Cloud SQL (PostgreSQL 17)")
        DATABASES = {
            'default': {
                'ENGINE': 'django.contrib.gis.db.backends.postgis',
                'NAME': os.getenv('NEW_DB_NAME'),
                'USER': os.getenv('NEW_DB_USER'),
                'PASSWORD': os.getenv('NEW_DB_PASSWORD'),
                'HOST': os.getenv('NEW_DB_HOST'),
                'PORT': os.getenv('NEW_DB_PORT'),
            }
        }
    else:
        print("🔹 Using local PostGIS (default)")
        DATABASES = {
            'default': {
                'ENGINE': 'django.contrib.gis.db.backends.postgis',
                'NAME': 'webmapping_db',
                'USER': 'aaronbaggot',
                'PASSWORD': '',
                'HOST': 'localhost',
                'PORT': '5432',
            }
        }


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# //DATABASES = {
#     'default': {
#         'ENGINE': 'django.contrib.gis.db.backends.postgis',
#         'NAME': 'trails_db',      #  match your docker-compose service
#         'USER': 'postgres',       # match docker-compose credentials
#         'PASSWORD': 'postgres',
#         'HOST': 'db',             # internal hostname for the Postgres container
#         'PORT': '5432',
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Open for development
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# CORS settings for development
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# API Documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'Trials API',
    'DESCRIPTION': 'RESTful API for trial data in Ireland',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    "CONTACT": {"name": "Aaron Baggot", "programme": "TU856", "Module": "Web Mapping", "email": "C22716399@mytudublin.ie"},
    "LICENSE": {"name": "MIT"},
    
    # Optional niceties:
    "COMPONENT_SPLIT_REQUEST": True,
    "SWAGGER_UI_SETTINGS": {"deepLinking": True, "displayOperationId": True},


}



LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (53.3498, -6.2603),  # Dublin coordinates
    'DEFAULT_ZOOM': 7,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,
    'SCALE': 'both',
}








